_target_: pytorch_lightning.Trainer

# set `1` to train on GPU, `0` to train on CPU only
gpus: [2]

min_epochs: 1
max_epochs: 200

amp_backend: "native" # auto mixed precsion
# gradient_clip_val : 5.0 # gradient cliping 
# accumulate_grad_batches: 4 # gradient accumulation

# number of validation steps to execute at the beginning of the training
num_sanity_val_steps: 2
log_every_n_steps: 1
# limit_valid_batches: 0

# ckpt path
resume_from_checkpoint: null
